Lesson 12 api
KayumovELdar/test-guru-r pull request #14
Opened 2021-02-16 17:06 UTC by KayumovELdar

2021-02-16 19:13 UTC, VidgarVii requested changes

2021-02-16 19:13 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +
Gist у тебя целая модель. Согласно rails соглашению для него правильней будет создать отдельный контроллер. Я экшен для создания гиста соответственно будет create

2021-02-16 19:13 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    flash_options = if result.success?
где у сервиса метод success?

2021-02-16 19:13 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  def initialize(question, client: nil)
можно сократить (question, client:)

2021-02-16 19:13 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +                      { notice: t('.success') }
Gist URL. Отображается хэш созданного gist в виде ссылки

2021-02-17 06:44 UTC, VidgarVii requested changes

2021-02-17 06:44 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +                                                         password_confirmation])
отступы съехали

2021-02-17 06:44 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  if result
этот result неочём ни говорит. От вызова любого метода будет какой-то результат. Даже если вернуть единицу, то результат будет положительный. Нужна логическая проверка.  
Например 
```
if result.success?
  ...
else
  ...
end
```

2021-02-17 06:44 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +      flash[:notice] = t('.success', url: result.html_url )
в сервисе нет такого метода html_url. Как другому разработчику понять как получить ссылку на гист?

2021-02-17 06:44 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +      flash[:notice] = t('.success', url: result.html_url )
не вижу чтобы url использовался

2021-02-17 06:48 UTC, VidgarVii requested changes

2021-02-17 06:48 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
[
  ...
].join()
сократит потребление памяти

2021-02-18 07:27 UTC, VidgarVii requested changes

2021-02-18 07:27 UTC, VidgarVii commented on app/controllers/admin/questions_controller.rb
>    before_action :find_test, only: %i[index create new]
что тут делает index?

2021-02-18 07:27 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    resource.is_a?(Admin) ? admin_tests_path : root_path
почему поменял?

2021-02-18 07:27 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +
не исправил

2021-02-18 07:27 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +      flash[:notice] = t('.success', result.url )
от куда берется url? что это за метод такой? И зачаем он в локализации, если он даже не используется

2021-02-19 07:29 UTC, VidgarVii requested changes

2021-02-19 07:29 UTC, VidgarVii commented on Gemfile
> +gem 'faraday'
а зачем тут faraday?

2021-02-19 07:29 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    @client.access_token
и зачем ты юзеру открывает свои секреты?

2021-02-19 07:29 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    @client.last_response.data.html_url.present?
мне кажется если вызвать  success до call то будет ошибка

2021-02-19 07:29 UTC, VidgarVii commented on app/views/admin/gists/_gist.html.erb
> +  <td><%= link_to gist_hash(gist.url), gist.url,
нет такого метода gist_hash
куда будет ввести ссылка?
проверяй всё руками!

2021-02-19 13:23 UTC, KayumovELdar commented on Gemfile
> +gem 'faraday'
когда делал по примеру его тут прописывали ?

2021-02-19 15:41 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +      flash[:notice] = t('.success', url: result[:html_url])
1 у result получение урла или id надо получать через метод
2 success не использует параметр url

2021-02-19 15:41 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
не исправил

2021-02-19 15:41 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    if result.last_response.html_url.present?
last_response.html_url.present? вот это должен проверять сервис. И возвращать ответ через метод success?

2021-02-20 11:03 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    if   gist_url.present?
дистанция 1,5 метра соблюдать не обязательно. А вот ruby style guid да

2021-02-20 11:03 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    gist_id = result.id
опять не понятно от куда берутся эти методы. 
Код должен быть явен. Без дополнительного изучения гема
Сделай так чтобы call возвращал объект который будет содержать нужные методы.

2021-02-21 17:49 UTC, merged