Lesson 6
KayumovELdar/test-guru-r pull request #7
Opened 2021-01-28 15:45 UTC by KayumovELdar

2021-01-28 17:16 UTC, VidgarVii requested changes

2021-01-28 17:16 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  def new
def new; end

2021-01-28 17:16 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +
все методы слелись. нужны отступы

2021-01-28 17:16 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +
нужен модификатор доступа. Так как не все методы являются экшенами

2021-01-28 17:16 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
`params.require(:question).permit(:text) ` должен быть в отдельном методе согласно rails way

2021-01-28 17:16 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    question = Question(params.require(:question).permit(:text))
тут у тебя явная ошибка. Видимо не проверял код

2021-01-28 17:16 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +<form action="/question" method="post"> #
ссылка не верная

2021-01-29 17:18 UTC, VidgarVii requested changes

2021-01-29 17:18 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +<form action="." method="post"> #
тут должен быть корректный путь

2021-01-29 17:18 UTC, VidgarVii commented on config/routes.rb
> +    resources :questions
половина экшенов не должно работать.

2021-01-30 15:38 UTC, VidgarVii requested changes

2021-01-30 15:38 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    question = @question
какой смысл инстанс переменную записывать в локальную переменную?

2021-01-30 15:38 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
Если вопрос на создастся (из-за валидации например) клиент этого не узнает. Надо добавить проверку записи ресурса в БД и далее действовать из ходя из результат
```
if @question.save
  redirect_to ...
else
  render :new
end
```

2021-01-31 18:22 UTC, KayumovELdar commented on app/controllers/questions_controller.rb
> +  end
стоп а что подправить осталось ?

2021-02-01 21:30 UTC, merged