Lesson 7
KayumovELdar/test-guru-r pull request #8
Opened 2021-02-02 19:51 UTC by KayumovELdar

2021-02-03 07:32 UTC, VidgarVii requested changes

2021-02-03 07:32 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      if @question.save
ты уже сохраняешь вопрос в 30 строке. Для проверки используй update

2021-02-03 07:32 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
не уверен что данный экшен работает. От куда тут может взяться тест? И какой вопрос пытаешься обновить?)

2021-02-03 07:32 UTC, VidgarVii commented on app/views/questions/_form.html.erb
> +    <% end %>
а зачем тогда 2 строка?

2021-02-03 07:32 UTC, VidgarVii commented on app/views/shared/_footer.html.erb
> +<th><%= link_to "Test_guru",'https://github.com/KayumovELdar/test-guru-r', rel: :nofollow, target: :_blank %></th>
1 тут должен вызываться хелпер
2 <th> тут не уместен

2021-02-03 07:32 UTC, VidgarVii commented on app/views/tests/show.html.erb
> +<% end %>
1 используй render collection
2 нужны ссылки чтобы можно было совершать действия над вопросом.

2021-02-03 16:33 UTC, VidgarVii requested changes

2021-02-03 16:33 UTC, VidgarVii commented on app/views/shared/_footer.html.erb
> +<th><%= link_to "Test_guru",'https://github.com/KayumovELdar/test-guru-r', rel: :nofollow, target: :_blank %></th>
**Для формирования ссылки на GitHub репозиторий: github_url(author, repo)**

2021-02-03 17:20 UTC, KayumovELdar commented on app/controllers/questions_controller.rb
> +  end
как понимаю нужно подправить данный edit ?

2021-02-04 06:03 UTC, VidgarVii requested changes

2021-02-04 06:03 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
сюда как попадает вопрос?)

2021-02-04 06:03 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question = Questions.find(params[:id])
у тебя ведь есть уже колбек для поиска вопроса

2021-02-04 06:03 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +      @test = Test.find(params[:id])
по гугли DRY и shotgun operation )

2021-02-04 06:03 UTC, VidgarVii commented on app/views/tests/index.html.erb
> +  <% @tests.each do |test| %>
используй render collection

2021-02-04 06:03 UTC, VidgarVii commented on app/views/shared/_footer.html.erb
> +</script>
нужен helper на руби

2021-02-04 06:03 UTC, VidgarVii commented on app/views/shared/_footer.html.erb
> +<th><%=github_url('KayumovELdar', 'test-guru-r'%></th>
а куда сам метод пропал?

2021-02-04 12:59 UTC, VidgarVii requested changes

2021-02-04 12:59 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    end
лучше объявляй метод там где действительно он нужен

2021-02-04 12:59 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    end
отступы съехали

2021-02-04 12:59 UTC, VidgarVii commented on app/views/questions/show.html.erb
> +<% question = Question.find(params[:id]) %>
нужный вопрос должен приходить из контроллера

2021-02-04 13:41 UTC, KayumovELdar commented on app/controllers/application_controller.rb
> +    end
то есть в вопросе и тесте ???? но это же повторение)))))))))

2021-02-04 13:48 UTC, KayumovELdar commented on app/controllers/application_controller.rb
> +    end
такое уточнение, дальше у нас примерно будет три блока схожих по содержанию. ответ, вопрос, и сам тест. Схоже будет создать удалить обновить итд.... я думаю сделать общий модуль с обобщенным текстом, только вопросс куда лучше будет данный файл поместить и через require_relative пришить

2021-02-05 06:11 UTC, VidgarVii requested changes

2021-02-05 06:11 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>    end
**Список вопросов теста должен выводиться на той же странице, что и сам тест**

этот экшен не нужен

2021-02-05 06:11 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  require_ralative 'Questions_controller'
не надо ни каких require_ralative в rails

2021-02-05 06:11 UTC, VidgarVii commented on app/views/questions/_form.html.erb
> +<% end %>
у тебя эта форма вызывается при обновлении вопроса. А для этого не нужен тест, соответственно и ссылка может быть некорректной
Пусть шапка формы создаётся отдельно для каждого макета. подлюкчай через партиал только поля формы

2021-02-05 06:11 UTC, VidgarVii commented on app/views/shared/_errors.html.erb
> +<%= if resource.errors.present? %>
= не нужна

2021-02-05 17:02 UTC, VidgarVii requested changes

2021-02-05 17:02 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.find(params[:id])
ряд экшенов не требует теста. Значит тут будет ошибка

2021-02-05 17:02 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>      @questioт.destroy
questioт

2021-02-05 17:02 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    render html: 'Вопрос удалён!'
по ТЗ нужно реализовать представления (и соответсвенно редиректы и рендеринги) для всех экшенов
посмотри еще раз скринкаст
подобный render html не используется

2021-02-08 12:02 UTC, merged